resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    buildDockerArtifact: false

trigger:
  batch: true
  branches:
    include:
      - development
      - release-*
      - master
      - hotfix-pipeline
